# Generated by Django 3.1.4 on 2021-01-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=64)),
                ('agent_create_time', models.DateTimeField(auto_now_add=True)),
                ('agent_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=64)),
                ('buyer_country', models.CharField(max_length=64)),
                ('buyer_paypal', models.EmailField(max_length=254)),
                ('buyer_profile', models.CharField(max_length=64)),
                ('buyer_create_time', models.DateTimeField(auto_now_add=True)),
                ('buyer_update_time', models.DateTimeField(auto_now=True)),
                ('buyer_agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='crm_admin.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_name', models.CharField(max_length=16, unique=True)),
                ('seller_wechat', models.CharField(max_length=64, unique=True)),
                ('seller_qq', models.CharField(max_length=64, unique=True)),
                ('seller_phone_number', models.CharField(max_length=64)),
                ('seller_create_time', models.DateTimeField(auto_now_add=True)),
                ('seller_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_country', models.CharField(max_length=64)),
                ('product_keywords', models.CharField(max_length=255)),
                ('product_sold_by', models.CharField(max_length=64)),
                ('product_asin', models.CharField(max_length=64)),
                ('product_link', models.CharField(max_length=64)),
                ('product_num_per_day', models.BigIntegerField()),
                ('product_num_total', models.BigIntegerField()),
                ('product_create_time', models.DateTimeField(auto_now_add=True)),
                ('product_update_time', models.DateTimeField(auto_now=True)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_admin.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_admin.buyer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_admin.product')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_country',
            field=models.ManyToManyField(to='crm_admin.Country'),
        ),
    ]
