# Generated by Django 3.1.4 on 2021-01-10 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_country',
            field=models.CharField(max_length=64, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_paypal',
            field=models.EmailField(max_length=254, verbose_name='Paypal'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_profile',
            field=models.CharField(max_length=64, verbose_name='亚马逊Profile'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=64, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_asin',
            field=models.CharField(max_length=64, verbose_name='Asin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_country',
            field=models.CharField(max_length=64, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_keywords',
            field=models.CharField(max_length=255, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(max_length=64, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_num_per_day',
            field=models.BigIntegerField(verbose_name='每日单数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_num_total',
            field=models.BigIntegerField(verbose_name='总单数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sold_by',
            field=models.CharField(max_length=64, verbose_name='店铺名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sell_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_phone_number',
            field=models.CharField(max_length=64, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_qq',
            field=models.CharField(max_length=64, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_wechat',
            field=models.CharField(max_length=64, unique=True, verbose_name='微信'),
        ),
    ]
